[workspace]
resolver = "3"
members = ["client","quote_lib", "server"]

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
rand = "0.9"
crossbeam = "0.8"
env_logger = "0.11"
log = "0.4"
ctrlc = "3.5"